[build]
  publish = "."

[[redirects]]
  from = "http://www.vilarinhotechsolutions.com.br/*"
  to = "http://vilarinhotechsolutions.com.br/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.vilarinhotechsolutions.com.br/*"
  to = "https://vilarinhotechsolutions.com.br/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
