-- Execute este script no SQL Editor do Supabase
-- 1) Tabela principal do portfolio
create table if not exists public.portfolio_projects (
  id bigint generated by default as identity primary key,
  fingerprint_key text not null,
  name text not null,
  type text not null,
  branch text,
  segmentation text,
  commercial_focus text,
  description text not null,
  url text,
  cover_url text,
  sort_order integer,
  is_published boolean not null default true,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint portfolio_projects_fingerprint_key_unique unique (fingerprint_key)
);

create index if not exists idx_portfolio_projects_published
  on public.portfolio_projects (is_published);

create index if not exists idx_portfolio_projects_sort_order
  on public.portfolio_projects (sort_order nulls last);

create index if not exists idx_portfolio_projects_updated_at
  on public.portfolio_projects (updated_at desc);

-- 2) Trigger para atualizar updated_at automaticamente
create or replace function public.set_updated_at_portfolio_projects()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_updated_at_portfolio_projects on public.portfolio_projects;
create trigger trg_set_updated_at_portfolio_projects
before update on public.portfolio_projects
for each row
execute function public.set_updated_at_portfolio_projects();

-- 3) RLS
alter table public.portfolio_projects enable row level security;

-- leitura publica para portfolio.html
create policy if not exists "portfolio_projects_public_read"
  on public.portfolio_projects
  for select
  using (is_published = true);

-- escrita para usuarios autenticados (painel admin via auth, service role ou regras custom)
create policy if not exists "portfolio_projects_auth_write"
  on public.portfolio_projects
  for all
  to authenticated
  using (true)
  with check (true);

-- 4) Bucket de imagens
insert into storage.buckets (id, name, public)
values ('portfolio-covers', 'portfolio-covers', true)
on conflict (id) do nothing;

-- permitir leitura publica das capas
create policy if not exists "portfolio_covers_public_read"
  on storage.objects
  for select
  using (bucket_id = 'portfolio-covers');

-- permitir upload para autenticados
create policy if not exists "portfolio_covers_auth_write"
  on storage.objects
  for all
  to authenticated
  using (bucket_id = 'portfolio-covers')
  with check (bucket_id = 'portfolio-covers');
